#!/bin/bash

get_decompressed_archive() {
	if [ .zip == ${1: -4} ]; then
		local decompressed_archive=${1%.zip}
	else
		local decompressed_archive=$(tar -tf $1 | head -n 1)
		decompressed_archive=${decompressed_archive%%/*}
	fi
	echo $decompressed_archive
}

# TODO: the build process can probably be put in here too
