#!/bin/bash

# https://slackware.uk/~urchlay/repos/ttf-console-fonts/ttf2psfu.sh

font_file_stripped=${1%.[ot]tf}
otf2bdf $1 -o tmp.bdf

# look into why this is needed
AV=$( sed -n 's,AVERAGE_WIDTH ,,p' tmp.bdf )
AV=$(( ( AV + 30 ) / 10 * 10 ))
sed -i "/AVERAGE_WIDTH/s, .*, $AV," tmp.bdf

BDF2PSF_SHARE=/usr/share/bdf2psf # Fonts directory from Debian's console-setup
SETS="\
	$BDF2PSF_SHARE/ascii.set+\
	$BDF2PSF_SHARE/linux.set+\
	$BDF2PSF_SHARE/fontsets/Lat2.256+\
	$BDF2PSF_SHARE/fontsets/Uni1.512+\
	$BDF2PSF_SHARE/useful.set\
	"
bdf2psf --fb tmp.bdf $BDF2PSF_SHARE/standard.equivalents $SETS 512 ${font_file_stripped}.psfu
