#!/bin/bash

parse_link() {
	package_archive=`basename ${1:?}`
	package_directory=${package_archive%%-[[:digit:]]*}
	source_directory="${LFS:-}/sources/$package_directory"
}

get_decompressed_archive() {
	local decompressed_archive=$(tar -tf $1 | head -n 1)
	decompressed_archive=${decompressed_archive%%/*}
	echo $decompressed_archive
}

do_download() {
	if [ $# -ne 1 ]; then
		echo "missing download URL for package"
		exit 1
	fi
	
	parse_link $@
	if [ ! -d $source_directory ]; then
		mkdir -pv $source_directory
		echo "created directory: $source_directory"
	fi
	
	pushd $source_directory > /dev/null
	if [ ! -e $package_archive ]; then
		wget $1
	fi
	
	decompressed_archive=$(get_decompressed_archive $package_archive)
	if [ ! -d $decompressed_archive ]; then
		tar -xf $package_archive
	fi
	
	pushd $decompressed_archive
}
