#!/bin/bash

DOWNLOAD_URL=https://download.savannah.gnu.org/releases/acl/acl-2.3.2.tar.xz

do_build() {
	./configure --prefix=/usr    \
	            --disable-static \
	            --docdir=/usr/share/doc/acl-2.3.2
	make
	make install
}
