#!/bin/bash

do_build() {
	if [ -e Makefile ]; then
		set +e
		make distclean
		set -e
	fi
	./configure --prefix=/usr             \
	            --without-bash-malloc     \
	            --with-installed-readline \
	            --docdir=/usr/share/doc/bash-5.3-rc2
	make
	make install
}
