#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/bash/bash-5.3-rc2.tar.gz

do_build() {
	./configure --prefix=/usr             \
	            --without-bash-malloc     \
	            --with-installed-readline \
	            --docdir=/usr/share/doc/bash-5.3-rc2
	make
	make install
}
