#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/coreutils/coreutils-9.7.tar.xz

do_build() {
	wget -P .. https://www.linuxfromscratch.org/patches/lfs/development/coreutils-9.7-upstream_fix-1.patch
	wget -P .. https://www.linuxfromscratch.org/patches/lfs/development/coreutils-9.7-i18n-1.patch
	patch -Np1 -i ../coreutils-9.7-upstream_fix-1.patch
	patch -Np1 -i ../coreutils-9.7-i18n-1.patch

	autoreconf -fv
	automake -af

	FORCE_UNSAFE_CONFIGURE=1 ./configure \
				--prefix=/usr            \
				--enable-no-install-program=kill,uptime
	make
	make install
	mv -v /usr/bin/chroot /usr/sbin
	mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
	sed -i 's/"1"/"8"/' /usr/share/man/man8/chroot.8
}
