#!/bin/bash

DOWNLOAD_URL=https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.47.2/e2fsprogs-1.47.2.tar.gz

do_build() {
	set +e
	mkdir -v build
	set -e
	cd build

	../configure --prefix=/usr       \
	             --sysconfdir=/etc   \
	             --enable-elf-shlibs \
	             --disable-libblkid  \
	             --disable-libuuid   \
	             --disable-uuidd     \
	             --disable-fsck
	make
	make install

	rm -fv /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a

	gunzip -v /usr/share/info/libext2fs.info.gz
	install-info --dir-file=/usr/share/info/dir /usr/share/info/libext2fs.info
	makeinfo -o      doc/com_err.info ../lib/et/com_err.texinfo
	install -v -m644 doc/com_err.info /usr/share/info
	install-info --dir-file=/usr/share/info/dir /usr/share/info/com_err.info
}
