#!/bin/bash

DOWNLOAD_URL=https://sourceware.org/ftp/elfutils/0.193/elfutils-0.193.tar.bz2

do_build() {
	./configure --prefix=/usr        \
				--disable-debuginfod \
				--enable-libdebuginfod=dummy
	make
	make -C libelf install
	install -vm644 config/libelf.pc /usr/lib/pkgconfig
	rm /usr/lib/libelf.a
}
