#!/bin/bash

DOWNLOAD_URL=https://github.com/libexpat/libexpat/releases/download/R_2_7_1/expat-2.7.1.tar.xz

do_build() {
	./configure --prefix=/usr \
				--disable-static \
				--docdir=/usr/share/doc/expat-2.7.1
	make
	make install
	install -v -m644 doc/*.{html,css} /usr/share/doc/expat-2.7.1
}
