#!/bin/bash

DOWNLOAD_URL=https://sourceforge.net/projects/expect/files/Expect/5.45.4/expect5.45.4.tar.gz

do_build() {
# TODO: python3 -c 'from pty import spawn; spawn(["echo", "ok"])'
	patch -Np1 -i ../expect-5.45.4-gcc15-1.patch
	./configure --prefix=/usr           \
            --with-tcl=/usr/lib     \
            --enable-shared         \
            --disable-rpath         \
            --mandir=/usr/share/man \
            --with-tclinclude=/usr/include
	
	make
	make install
	ln -svf expect5.45.4/libexpect5.45.4.so /usr/lib
}
