#!/bin/bash

do_build() {
	pty_result=$(python3 -c 'from pty import spawn; spawn(["echo", "ok"])')
	if [ "ok" != $pty_result ]; then
		echo "failed spawning pty during 'expect' installation: $pty_result"
		exit 1
	fi
	set +e
	patch -Np1 -i ../expect-5.45.4-gcc15-1.patch
	set -e
	./configure --prefix=/usr           \
            --with-tcl=/usr/lib     \
            --enable-shared         \
            --disable-rpath         \
            --mandir=/usr/share/man \
            --with-tclinclude=/usr/include
	
	make
	make install
	ln -svf expect5.45.4/libexpect5.45.4.so /usr/lib
}
