#!/bin/bash

do_build() {
	case $(uname -m) in
		x86_64)
			sed -e '/m64=/s/lib64/lib/' \
				-i.orig gcc/config/i386/t-linux64
			;;
	esac

	set +e
	mkdir -v build-chroot
	set -e
	cd build-chroot

	../configure --prefix=/usr            \
	             LD=ld                    \
	             --enable-languages=c,c++,go \
	             --enable-default-pie     \
	             --enable-default-ssp     \
	             --enable-host-pie        \
	             --disable-multilib       \
	             --disable-bootstrap      \
	             --disable-fixincludes    \
	             --with-system-zlib
	make
	ulimit -s -H unlimited
	sed -e '/cpython/d'               -i ../gcc/testsuite/gcc.dg/plugin/plugin.exp
	sed -e 's/no-pic /&-no-pie /'     -i ../gcc/testsuite/gcc.target/i386/pr113689-1.c
	sed -e 's/300000/(1|300000)/'     -i ../libgomp/testsuite/libgomp.c-c++-common/pr109062.c
	sed -e 's/{ target nonpic } //' \
	    -e '/GOTPCREL/d'              -i ../gcc/testsuite/gcc.target/i386/fentryname3.c

	make install
	ln -svr /usr/bin/cpp /usr/lib
	ln -sv gcc.1 /usr/share/man/man1/cc.1
	ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/15.1.0/liblto_plugin.so \
			/usr/lib/bfd-plugins/
	mkdir -pv /usr/share/gdb/auto-load/usr/lib
	mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib
}
