#!/bin/bash

do_build() {
	if [ -e Makefile ]; then
		set +e
		make distclean
		set -e
	fi

	if [ -v DO_SECOND_PASS ]; then
		./configure --prefix=/usr    \
				--disable-static \
				--docdir=/usr/share/doc/gettext-0.25
		make
		make install
		chmod -v 0755 /usr/lib/preloadable_libintl.so
	else
		./configure --disable-shared
		make
		cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
	fi
}
