#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/gettext/gettext-0.25.tar.xz

do_build() {
	if [ -v DO_SECOND_PASS ]; then
		./configure --prefix=/usr    \
				--disable-static \
				--docdir=/usr/share/doc/gettext-0.25
		make
		make install
		chmod -v 0755 /usr/lib/preloadable_libintl.so
	else
		./configure --disable-shared
		
		cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
	fi
}
