#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz

do_build() {
	sed -i '/long long t1;/,+1s/()/(...)/' configure

	./configure --prefix=/usr    \
	            --enable-cxx     \
	            --disable-static \
	            --docdir=/usr/share/doc/gmp-6.3.0
	make
	make html
	make install
	make install-html
}
