#!/bin/bash

do_build() {
	local font_directory=/usr/share/fonts/unifont
	if [ ! -d $font_directory ]; then
		mkdir -pv $font_directory
	fi
	gunzip -c ../unifont-16.0.01.pcf.gz > /usr/share/fonts/unifont/unifont.pcf

	unset {C,CPP,CXX,LD}FLAGS

	echo depends bli part_gpt > grub-core/extra_deps.lst

	./configure --prefix=/usr     \
				--sysconfdir=/etc \
				--disable-efiemu  \
				--target=x86_64 \
				--with-platform=efi \
				--disable-werror
	make
	make install
	mv -v /etc/bash_completion.d/grub /usr/share/bash-completion/completions

	install -vm755 grub-mkfont /usr/bin/ &&
	install -vm644 ascii.h widthspec.h *.pf2 /usr/share/grub/

	modify_kernel_config "CONFIG_EFI=y" "CONFIG_EFI_STUB=y" "CONFIG_BLOCK=y" "CONFIG_PARTITION_ADVANCED=y" \
			     "CONFIG_EFI_PARTITION=y" "CONFIG_VFAT_FS=y" "CONFIG_EFIVAR_FS=y" "CONFIG_NLS=y" \
			     "CONFIG_NLS_CODEPAGE_437=y" "CONFIG_NLS_ISO8859_1=y"

	mountpoint /boot/efi || mount --mkdir -v -t vfat $LFS_EFI_DEVICE -o codepage=437,iocharset=iso8859-1 /boot/efi
	mountpoint /sys/firmware/efi/efivars || mount -v -t efivarfs efivarfs /sys/firmware/efi/efivars
	grub-install --bootloader-id=LFS --recheck
}
