#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/inetutils/inetutils-2.6.tar.xz

do_build() {
	sed -i 's/def HAVE_TERMCAP_TGETENT/ 1/' telnet/telnet.c

	./configure --prefix=/usr        \
	            --bindir=/usr/bin    \
	            --localstatedir=/var \
	            --disable-logger     \
	            --disable-whois      \
	            --disable-rcp        \
	            --disable-rexec      \
	            --disable-rlogin     \
	            --disable-rsh        \
	            --disable-servers
	make
	make install
	mv -v /usr/{,s}bin/ifconfig
}
