#!/bin/bash

DOWNLOAD_URL=https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-6.15.0.tar.xz

do_build() {
	sed -i /ARPD/d Makefile
	rm -fv man/man8/arpd.8

	make NETNS_RUN_DIR=/run/netns
	make SBINDIR=/usr/sbin install
	install -vDm644 COPYING README* -t /usr/share/doc/iproute2-6.15.0
}
