#!/bin/bash

DOWNLOAD_URL=https://pypi.org/packages/source/J/Jinja2/jinja2-3.1.6.tar.gz

do_build() {
	pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
	pip3 install --no-index --find-links dist Jinja2
}
