#!/bin/bash

DOWNLOAD_URL=https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-34.2.tar.xz

do_build() {
	mkdir -p build
	cd       build
	
	meson setup --prefix=/usr ..    \
	            --buildtype=release \
	            -D manpages=false
	ninja
	ninja install
}
