#!/bin/bash

cat > /etc/fstab << "EOF"
# Begin /etc/fstab

# file system	mount-point	type	options				dump	fsck
#																order
EOF

for mountpoint in / /boot/efi; do
	mount_info=$(mount -l | grep "on $mountpoint type")
	mount_device=$(echo $mount_info | cut -d' ' -f 1)
	filesystem_type=$(echo $mount_info | cut -d' ' -f 5)
	device_uuid=$(lsblk --output UUID,PATH | grep "$mount_device" | cut -d' ' -f 1)
	fstab_info="UUID=$device_uuid	$mountpoint	$filesystem_type	"
	if [ "$filesystem_type" == "ext4" ]; then
		fstab_info+="defaults	1	1"
	elif [ "$filesystem_type" == "vfat" ]; then
		fstab_info+="codepage=437,iocharset=iso8859-1	0	1"
	else
		echo "Unexpected filesystem type: $mount_info"
		exit 1
	fi
	echo "$fstab_info" >> /etc/fstab
done

echo "# End /etc/fstab" >> /etc/fstab
