#!/bin/bash

DOWNLOAD_URL=https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.76.tar.xz

do_build() {
	sed -i '/install -m.*STA/d' libcap/Makefile
	make prefix=/usr lib=lib
	make prefix=/usr lib=lib install
}
