#!/bin/bash

do_build() {
	./configure --prefix=/usr \
		--sysconfdir=/etc \
		--disable-static
	make
	make install

	mkdir -vp /usr/share/doc/libnl-3.11.0 &&
	tar -xf ../libnl-doc-3.11.0.tar.gz --strip-components=1 --no-same-owner \
		-C  /usr/share/doc/libnl-3.11.0
}
