#!/bin/bash

DOWNLOAD_URL=https://github.com/besser82/libxcrypt/releases/download/v4.4.38/libxcrypt-4.4.38.tar.xz

do_build() {
	./configure --prefix=/usr                \
	            --enable-hashes=strong,glibc \
	            --enable-obsolete-api=no     \
	            --disable-static             \
	            --disable-failure-tokens
	make
	make install
}
