#!/bin/bash

do_build() {
#TODO: get docs
	mkdir build
	cd build
	meson setup .. \
				--prefix=/usr \
				--buildtype=release \
				-D docdir=/usr/share/doc/Linux-PAM-1.7.1
	ninja
	ninja install
	chmod -v 4755 /usr/sbin/unix_chkpwd

	install -v -m755 -d /etc/pam.d
	cp /chroot-scripts/extras/{system-account,system-auth,system-session,system-password,other} /etc/pam.d
}
