#!/bin/bash

DOWNLOAD_URL=https://github.com/linux-pam/linux-pam/releases/download/v1.7.1/Linux-PAM-1.7.1.tar.xz

do_build() {
#TODO: get docs
	mkdir build
	cd build
	meson setup .. \
				--prefix=/usr \
				--buildtype=release \
				-D docdir=/usr/share/doc/Linux-PAM-1.7.1
	ninja
	ninja install
	chmod -v 4755 /usr/sbin/unix_chkpwd

	install -v -m755 -d /etc/pam.d
	local extras=/chroot-scripts/extras
	cp /chroot-scripts/extras/{system-account,system-auth,system-session,system-password,other} /etc/pam.d
}
