#!/bin/bash

#. /chroot-scripts/ORDERED_SCRIPTS
STEPS=(lfs-copy ${LFS_PACKAGE_BUILD_ORDER//:/" "} lfs-cleanup lfs-setup-font lfs-setup-profile lfs-create-fstab)
echo steps are ${STEPS[@]}

set -e
set -u
set -x

. /chroot-scripts/setup-script-environment
pushd /sources
for step in ${STEPS[@]}; do
	(
		. /chroot-scripts/$step
		if [ ! -z ${step##lfs-*} ]; then
			package=${PACKAGE:-${step%-pass2}}
			download_url=$(cat /chroot-scripts/PACKAGES | grep "^$package" | awk '{print $2}')
			parse_link $download_url
			pushd $source_directory
			decompressed_archive=$(get_decompressed_archive $package_archive)
			pushd ${decompressed_archive:?variable is not set}
			do_build
		fi
	)
done
