#!/bin/bash

. /chroot-scripts/PACKAGES
STEPS=(lfs-copy ${SCRIPTS[@]} lfs-cleanup lfs-setup-font lfs-setup-profile lfs-create-fstab)
set -e
set -u

. /chroot-scripts/setup-script-environment
pushd /sources
for step in ${STEPS[@]}; do
	(
		. /chroot-scripts/$step
		if [ ! -z ${step##lfs-*} ]; then
			parse_link $DOWNLOAD_URL
			decompressed_archive=$(get_decompressed_archive $package_archive)
			pushd $decompressed_archive
			do_build
		fi
	)
done
