#!/bin/bash

DOWNLOAD_URL=https://pypi.org/packages/source/M/MarkupSafe/markupsafe-3.0.2.tar.gz

do_build() {
	pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
	pip3 install --no-index --find-links dist Markupsafe
}
