#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz

do_build() {
	./configure --prefix=/usr    \
	            --disable-static \
	            --docdir=/usr/share/doc/mpc-1.3.1
	make
	make html
	make install
	make install-html
}
