#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.2.tar.xz

do_build() {
	./configure --prefix=/usr        \
	            --disable-static     \
	            --enable-thread-safe \
	            --docdir=/usr/share/doc/mpfr-4.2.2
	make
	make html
	make install
	make install-html
}
