#!/bin/bash

do_build() {
	./configure --prefix=/usr     \
	            --disable-static  \
	            --enable-lib-only \
	            --docdir=/usr/share/doc/nghttp2-1.66.0 &&
	make
	make install
}
