#!/bin/bash

DOWNLOAD_URL=https://github.com/ninja-build/ninja/archive/v1.13.0/ninja-1.13.0.tar.gz

do_build() {
	sed -i '/int Guess/a \
	  int   j = 0;\
	  char* jobs = getenv( "NINJAJOBS" );\
	  if ( jobs != NULL ) j = atoi( jobs );\
	  if ( j > 0 ) return j;\
	' src/ninja.cc

	python3 configure.py --bootstrap --verbose
	install -vm755 ninja /usr/bin/
	install -vDm644 misc/bash-completion /usr/share/bash-completion/completions/ninja
	install -vDm644 misc/zsh-completion  /usr/share/zsh/site-functions/_ninja
}
