#!/bin/bash

DOWNLOAD_URL=https://github.com/openssl/openssl/releases/download/openssl-3.5.1/openssl-3.5.1.tar.gz

do_build() {
	./config --prefix=/usr         \
	         --openssldir=/etc/ssl \
	         --libdir=lib          \
	         shared                \
	         zlib-dynamic
	make
	sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
	make MANSUFFIX=ssl install
	mv -v /usr/share/doc/openssl /usr/share/doc/openssl-3.5.0
	cp -vfr doc/* /usr/share/doc/openssl-3.5.0
}
