#!/bin/bash

DOWNLOAD_URL=https://files.pythonhosted.org/packages/source/p/packaging/packaging-25.0.tar.gz

do_build() {
	pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
	pip3 install --no-index --find-links dist packaging
}
