#!/bin/bash

DOWNLOAD_URL=https://www.cpan.org/src/5.0/perl-5.41.9.tar.xz

do_build() {
	sh Configure -des                                         \
	             -D prefix=/usr                               \
	             -D vendorprefix=/usr                         \
	             -D useshrplib                                \
	             -D privlib=/usr/lib/perl5/5.41/core_perl     \
	             -D archlib=/usr/lib/perl5/5.41/core_perl     \
	             -D sitelib=/usr/lib/perl5/5.41/site_perl     \
	             -D sitearch=/usr/lib/perl5/5.41/site_perl    \
	             -D vendorlib=/usr/lib/perl5/5.41/vendor_perl \
	             -D vendorarch=/usr/lib/perl5/5.41/vendor_perl
	
	make
	make install
}
