#!/bin/bash

do_build() {
	export BUILD_ZLIB=False
	export BUILD_BZIP2=0
	configure_args=(-des \
	             -D prefix=/usr \
	             -D vendorprefix=/usr \
	             -D useshrplib \
	             -D privlib=/usr/lib/perl5/5.42/core_perl \
	             -D archlib=/usr/lib/perl5/5.42/core_perl \
	             -D sitelib=/usr/lib/perl5/5.42/site_perl \
	             -D sitearch=/usr/lib/perl5/5.42/site_perl \
	             -D vendorlib=/usr/lib/perl5/5.42/vendor_perl \
	             -D vendorarch=/usr/lib/perl5/5.42/vendor_perl)
	if [ -v DO_SECOND_PASS ]; then
		for arg in man1dir=/usr/share/man/man1 \
			   man3dir=/usr/share/man/man3 \
			   pager='"/usr/bin/less -isR"' \
			   usethreads; do
			configure_args[${#configure_args[@]}]="-D $arg"
		done
	fi

	if [ -e Makefile ]; then
		set +e
		make distclean
		set -e
	fi

	sh Configure "${configure_args[@]}"
	make
	make install
}
