#!/bin/bash

DOWNLOAD_URL=https://distfiles.ariadne.space/pkgconf/pkgconf-2.5.1.tar.xz

do_build() {
	./configure --prefix=/usr \
				--disable-static \
				--docdir=/usr/share/doc/pkgconf-2.5.1
	make
	make install

	ln -sv pkgconf   /usr/bin/pkg-config
	ln -sv pkgconf.1 /usr/share/man/man1/pkg-config.1
}
