#!/bin/bash

do_build() {
	./configure --prefix=/usr                           \
	            --docdir=/usr/share/doc/procps-ng-4.0.5 \
	            --disable-static                        \
	            --disable-kill                          \
	            --enable-watch8bit                      \
	            --with-systemd
	make
	make install
}
