#!/bin/bash

do_build() {
	configure_args="--prefix=/usr       \
		            --enable-shared     \
		            --without-static-libpython"
	if [ -v DO_SECOND_PASS ]; then
		configure_args+=" --with-system-expat --enable-optimizations"
	else
		configure_args+=" --without-ensurepip"
	fi

	if [ -e Makefile ]; then
		set +e
		make distclean
		set -e
	fi

	./configure $configure_args
	make
	make install
}
