#!/bin/bash

DOWNLOAD_URL=https://www.python.org/ftp/python/3.13.5/Python-3.13.5.tar.xz

do_build() {
	./configure --prefix=/usr       \
	            --enable-shared     \
	            --without-ensurepip \
	            --without-static-libpython
	
	make
	make install
}
