#!/bin/bash

DOWNLOAD_URL=https://www.python.org/ftp/python/3.13.5/Python-3.13.5.tar.xz

do_build() {
	configure_args="--prefix=/usr       \
		            --enable-shared     \
		            --without-static-libpython"
	if [ -v DO_SECOND_PASS ]; then
		configure_args+=" --with-system-expat --enable-optimizations"
	else
		configure_args+=" --without-ensurepip"
	fi

	./configure $configure_args
	make
	make install
}
