#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/readline/readline-8.3-rc2.tar.gz

do_build() {
	sed -i '/MV.*old/d' Makefile.in
	sed -i '/{OLDSUFF}/c:' support/shlib-install
	
	sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf

	./configure --prefix=/usr \
				--disable-static \
				--with-curses \
				--docdir=/usr/share/doc/readline-8.3-rc2
	make SHLIB_LIBS="-lncursesw"
	make install
	install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-8.3-rc2
}
