#!/bin/bash

do_build() {
	if [ -e Makefile ]; then
		set +e
		make distclean
		set -e
	fi

	./configure --prefix=/usr
	make
	make html
	make install
	install -d -m755 /usr/share/doc/sed-4.9
	install -m644 doc/sed.html /usr/share/doc/sed-4.9
}
