#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/sed/sed-4.9.tar.xz

do_build() {
	./configure --prefix=/usr
	make
	make html
	make install
	install -d -m755 /usr/share/doc/sed-4.9
	install -m644 doc/sed.html /usr/share/doc/sed-4.9
}
