#!/bin/bash

DOWNLOAD_URL=https://pypi.org/packages/source/s/setuptools/setuptools-80.9.0.tar.gz

do_build() {
	pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
	pip3 install --no-index --find-links dist setuptools
}
