#!/bin/bash

do_build() {
	sed -i 's/groups$(EXEEXT) //' src/Makefile.in

	find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
	find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
	find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;
	
	sed -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD YESCRYPT@' \
	    -e 's@/var/spool/mail@/var/mail@'                   \
	    -e '/PATH=/{s@/sbin:@@;s@/bin:@@}'                  \
	    -i etc/login.defs

	touch /usr/bin/passwd
	./configure --sysconfdir=/etc   \
	            --disable-static    \
	            --without-libbsd    \
	            --with-{b,yes}crypt \
				--with-group-name-max-length=32
	make

	make exec_prefix=/usr pamddir= install
	make -C man install-man
	install -v -m644 /etc/login.defs /etc/login.defs.orig &&
	for FUNCTION in FAIL_DELAY               \
	                FAILLOG_ENAB             \
	                LASTLOG_ENAB             \
	                MAIL_CHECK_ENAB          \
	                OBSCURE_CHECKS_ENAB      \
	                PORTTIME_CHECKS_ENAB     \
	                QUOTAS_ENAB              \
	                CONSOLE MOTD_FILE        \
	                FTMP_FILE NOLOGINS_FILE  \
	                ENV_HZ PASS_MIN_LEN      \
	                SU_WHEEL_ONLY            \
	                PASS_CHANGE_TRIES        \
	                PASS_ALWAYS_WARN         \
	                CHFN_AUTH ENCRYPT_METHOD \
	                ENVIRON_FILE
	do
	    sed -i "s/^${FUNCTION}/# &/" /etc/login.defs
	done

	pushd /chroot-scripts/extras/etc
	cp -v --parents pam.d/{login,passwd,su,chpasswd,newusers,chage} /etc
	popd

	for PROGRAM in chfn chgpasswd chsh groupadd groupdel \
               groupmems groupmod useradd userdel usermod
	do
	    install -v -m644 /etc/pam.d/chage /etc/pam.d/${PROGRAM}
	    sed -i "s/chage/$PROGRAM/" /etc/pam.d/${PROGRAM}
	done

	if [ -f /etc/login.access ]; then mv -v /etc/login.access{,.NOUSE}; fi
	if [ -f /etc/limits ]; then mv -v /etc/limits{,.NOUSE}; fi

	pwconv
	grpconv

	mkdir -pv /etc/default
	useradd -D --gid 999
	passwd root
}
