#!/bin/bash

do_build() {
	sed -e 's/GROUP="render"/GROUP="video"/' \
	    -e 's/GROUP="sgx", //'               \
	    -i rules.d/50-udev-default.rules.in
	
	set +e
	mkdir -p build
	set -e
	cd build

	meson setup ..                \
			--prefix=/usr         \
			--buildtype=release      \
			-D default-dnssec=no     \
			-D firstboot=false       \
			-D install-tests=false   \
			-D ldconfig=false        \
			-D man=auto              \
			-D sysusers=false        \
			-D rpmmacrosdir=no       \
			-D homed=disabled        \
			-D userdb=false          \
			-D mode=release          \
			-D pam=enabled           \
			-D pamconfdir=/etc/pam.d \
			-D dev-kvm-mode=0660     \
			-D nobody-group=nogroup  \
			-D sysupdate=disabled    \
			-D ukify=disabled        \
			-D docdir=/usr/share/doc/systemd-257.7
	ninja
	ninja install

	cp /chroot-scripts/extras/systemd-user /etc/pam.d
	systemd-machine-id-setup
	systemctl preset-all
}
