#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz

do_build() {
	FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr
	make
	make install
	make -C doc install-html docdir=/usr/share/doc/tar-1.35
}
