#!/bin/bash

do_build() {
	if [ -e Makefile ]; then
		set +e
		make distclean
		set -e
	fi

	FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr
	make
	make install
	make -C doc install-html docdir=/usr/share/doc/tar-1.35
}
