#!/bin/bash

DOWNLOAD_URL=https://sourceforge.net/projects/tcl/files/Tcl/9.0.1/tcl9.0.1-src.tar.gz

do_build() {
	SRCDIR=$(pwd)
	cd unix

	./configure --prefix=/usr \
				--mandir=/usr/share/man \
				--disable-rpath
	
	make
	sed -e "s|$SRCDIR/unix|/usr/lib|" \
    -e "s|$SRCDIR|/usr/include|"  \
    -i tclConfig.sh

	sed -e "s|$SRCDIR/unix/pkgs/tdbc1.1.10|/usr/lib/tdbc1.1.10|" \
	    -e "s|$SRCDIR/pkgs/tdbc1.1.10/generic|/usr/include|"     \
	    -e "s|$SRCDIR/pkgs/tdbc1.1.10/library|/usr/lib/tcl8.6|"  \
	    -e "s|$SRCDIR/pkgs/tdbc1.1.10|/usr/include|"             \
	    -i pkgs/tdbc1.1.10/tdbcConfig.sh
	
	sed -e "s|$SRCDIR/unix/pkgs/itcl4.3.2|/usr/lib/itcl4.3.2|" \
	    -e "s|$SRCDIR/pkgs/itcl4.3.2/generic|/usr/include|"    \
	    -e "s|$SRCDIR/pkgs/itcl4.3.2|/usr/include|"            \
	    -i pkgs/itcl4.3.2/itclConfig.sh
	
	unset SRCDIR
	make install
	chmod -v u+w /usr/lib/libtcl9.0.so
	make install-private-headers
	ln -sfv tclsh9.0 /usr/bin/tclsh
	mv /usr/share/man/man3/{Thread,Tcl_Thread}.3
	cd ..
	tar -xf ../tcl9.0.1-html.tar.gz --strip-components=1
	mkdir -v -p /usr/share/doc/tcl-9.0.1
	cp -v -r  ./html/* /usr/share/doc/tcl-9.0.1
}
