#!/bin/bash

do_build() {
	if [ -e Makefile ]; then
		set +e
		make distclean
		set -e
	fi

	./configure --prefix=/usr
	make
	make install
	if [ -v DO_SECOND_PASS ]; then make TEXMF=/usr/share/texmf install-tex; fi
}
