#!/bin/bash

DOWNLOAD_URL=https://ftp.gnu.org/gnu/texinfo/texinfo-7.2.tar.xz

do_build() {
	./configure --prefix=/usr
	make
	make install
	if [ -v DO_SECOND_PASS ]; then make TEXMF=/usr/share/texmf install-tex; fi
}
