#!/bin/bash

do_build() {
	sed -i '/calver/s/^/#/;$iversion="2025.4.11.15"' setup.py
	pip3 wheel -w dist --no-build-isolation --no-deps --no-cache-dir $PWD
	pip3 install --no-index --find-links dist --no-user trove-classifiers
}
