#!/bin/bash

DOWNLOAD_URL=https://www.kernel.org/pub/linux/utils/util-linux/v2.41/util-linux-2.41.1.tar.xz

do_build() {
	set +e
	mkdir -pv /var/lib/hwclock
	set -e
	
	./configure --libdir=/usr/lib     \
	            --runstatedir=/run    \
	            --disable-chfn-chsh   \
	            --disable-login       \
	            --disable-nologin     \
	            --disable-su          \
	            --disable-setpriv     \
	            --disable-runuser     \
	            --disable-pylibmount  \
	            --disable-static      \
	            --disable-liblastlog2 \
	            --without-python      \
	            ADJTIME_PATH=/var/lib/hwclock/adjtime \
	            --docdir=/usr/share/doc/util-linux-2.41
	
	make
	make install
}
