#!/bin/bash

DOWNLOAD_URL=https://pypi.org/packages/source/w/wheel/wheel-0.46.1.tar.gz

do_build() {
	pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
	pip3 install --no-index --find-links dist wheel
}
