#!/bin/bash

DOWNLOAD_URL=https://github.com/tukaani-project/xz/releases/download/v5.8.1/xz-5.8.1.tar.xz

do_build() {
	./configure --prefix=/usr    \
				--disable-static \
				--docdir=/usr/share/doc/xz-5.8.1

	make
	make install
}
