#!/bin/bash

DOWNLOAD=https://ftp.gnu.org/gnu/findutils/findutils-4.10.0.tar.xz

function build {
	./configure --prefix=/usr \
				--localstatedir=/var/lib/locate \
				--host=$LFS_TGT \
				--build=$(build-aux/config.guess) && make && make DESTDIR=$LFS install
}
