#!/bin/bash

DOWNLOAD=https://github.com/tukaani-project/xz/releases/download/v5.8.1/xz-5.8.1.tar.xz

function build {
	./configure --prefix=/usr \
				--host=$LFS_TGT \
				--build=$(build-aux/config.guess) \
				--disable-static \
				--docdir=/usr/share/doc/xz-5.8.1 && make && make DESTDIR=$LFS install
	rm -v $LFS/usr/lib/liblzma.la
}
