#!/bin/bash

DOWNLOAD=https://git.kernel.org/torvalds/t/linux-6.15.tar.gz

function build {
	make mrproper

	make headers
	find usr/include -type f ! -name "*.h" -delete
	cp -rv usr/include $LFS/usr
}
