#!/bin/bash

DOWNLOAD=https://ftp.gnu.org/gnu/bash/bash-5.3-rc2.tar.gz

function build {
	./configure --prefix=/usr \
				--build=$(sh support/config.guess) \
				--host=$LFS_TGT \
				--without-bash-malloc && make && make DESTDIR=$LFS install

	ln -sv bash $LFS/bin/sh
}
