#!/bin/bash

DOWNLOAD=https://ftp.gnu.org/gnu/diffutils/diffutils-3.12.tar.xz

function build {
	./configure --prefix=/usr \
				--host=$LFS_TGT \
				gl_cv_func_strcasecmp_works=y \
				--build=$(./build-aux/config.guess) && make && make DESTDIR=$LFS install
}
