#!/bin/bash

function build {
	./configure --prefix=/usr \
				--build=$(sh support/config.guess) \
				--host=$LFS_TGT \
				--without-bash-malloc && make && make DESTDIR=$LFS install

	ln -svf bash $LFS/bin/sh
}
