#!/bin/bash

BUILD_PASS1_DIR=build-pass1
BUILD_PASS2_DIR=build-pass2

function do_pass1 {
	sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
	
	if [ ! -d $BUILD_PASS1_DIR ]; then
		mkdir -v $BUILD_PASS1_DIR
	fi
	pushd $BUILD_PASS1_DIR > /dev/null

	../configure --target=$LFS_TGT \
				 --prefix=$LFS/tools \
				 --with-glibc-version=2.41 \
				 --with-sysroot=$LFS \
				 --with-newlib \
				 --without-headers \
				 --enable-default-pie \
				 --enable-default-ssp \
				 --disable-nls \
				 --disable-shared \
				 --disable-multilib \
				 --disable-threads \
				 --disable-libatomic \
				 --disable-libgomp \
				 --disable-libquadmath \
				 --disable-libssp \
				 --disable-libvtv \
				 --disable-libstdcxx \
				 --enable-languages=c,c++ && make && make install
	popd > /dev/null
	cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
		`dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include/limits.h
}

function do_pass2 {
	sed '/thread_header =/s/@.*@/gthr-posix.h/' -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

	if [ ! -d $BUILD_PASS2_DIR ]; then
		mkdir -v $BUILD_PASS2_DIR
	fi
	pushd $BUILD_PASS2_DIR > /dev/null

	../configure --build=$(../config.guess) \
				 --host=$LFS_TGT \
				 --target=$LFS_TGT \
				 LDFLAGS_FOR_TARGET=-L$PWD/$LFS_TGT/libgcc \
				 --prefix=/usr \
				 --with-build-sysroot=$LFS \
				 --enable-default-pie \
				 --enable-default-ssp \
				 --disable-nls \
				 --disable-multilib \
				 --disable-libatomic \
				 --disable-libgomp \
				 --disable-libquadmath \
				 --disable-libsanitizer \
				 --disable-libssp \
				 --disable-libvtv \
				 --enable-languages=c,c++ && make && make DESTDIR=$LFS install
	ln -sv gcc $LFS/usr/bin/cc
	popd > /dev/null
}

function get_dependencies {
	local sources_dir=${LFS:-}/sources
	for package in mpfr mpc gmp; do
		if [ ! -d $package ]; then
			local url=$(cat $PACKAGES_PATH | grep "^$package" | awk '{ print $2 }')
			local archive=$(basename $url)
			pushd $sources_dir/$package
			local decompressed_archive=$(get_decompressed_archive $archive)
			popd
			tar -xf $sources_dir/$package/$archive
			mv -v $decompressed_archive $package
		fi
	done
}

function build {
	get_dependencies
	if [ ! -v enable_pass2 ]; then
		do_pass1
	else
		do_pass2
	fi
}
