#!/bin/bash

function build {
	ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64
	ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64/ld-lsb-x86-64.so.3

	set +e
	patch -Np1 -i ../glibc-2.41-fhs-1.patch
	set -e

	if [ ! -d build ]; then
		mkdir -v build
	fi
	pushd build > /dev/null

	../configure --prefix=/usr \
				 --host=$LFS_TGT \
				 --build=$(../scripts/config.guess) \
				 --enable-kernel=6.14 \
				 --disable-nscd \
				 --enable-sframe \
				 libc_cv_slibdir=/usr/lib && make && make DESTDIR=$LFS install
	popd > /dev/null

	sed '/RTLDLIST=/s@/usr@@g' -i $LFS/usr/bin/ldd
}
